aiderignore: /home/thf/usr/src/Bevans/wizzy/.aiderignore
analytics: no
analytics-disable: False
apply-clipboard-edits: False
assistant-output-color: #0088ff
attribute-author: True
attribute-commit-message-author: False
attribute-commit-message-committer: False
attribute-committer: True
auto-commits: True
auto-lint: True
auto-test: False
cache-keepalive-pings: 0
cache-prompts: False
chat-history-file: /home/thf/usr/src/Bevans/wizzy/.aider.chat.history.md
check-update: True
code-theme: default
commit: False
dark-mode: False
detect-urls: True
dirty-commits: True
dry-run: False
encoding: utf-8
env-file: /home/thf/usr/src/Bevans/wizzy/.env
exit: False
fancy-input: True
files: []
git: True
gitignore: True
gui: False
input-history-file: /home/thf/usr/src/Bevans/wizzy/.aider.input.history
install-main-branch: False
just-check-update: False
light-mode: False
lint: False
lint-cmd: []
map-multiplier-no-files: 2
map-refresh: auto
map-tokens: 1024
model: openai/qwen2.5-coder-14b-instruct
model-metadata-file: .aider.model.metadata.json
model-settings-file: .aider.model.settings.yml
openai-api-base: http://localhost:5000/v1
pretty: True
restore-chat-history: False
show-diffs: False
show-model-warnings: False
show-prompts: False
show-repo-map: False
skip-sanity-check-repo: False
stream: True
subtree-only: False
suggest-shell-commands: True
test: False
tool-error-color: #FF2222
tool-warning-color: #FFA500
upgrade: False
user-input-color: #00cc00
verbose: False
verify-ssl: True
vim: True
voice-format: wav
voice-language: en
