---
name: PlatforIO CI - arm64

on:
  push:
    branches:
      - master
      - develop
      - 'feat/*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: gentoo-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.CLONE_TOKEN }}"

      - name: Build
        run: make

      - name: Send a Telegram message on failure
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
        if: ${{ failure() }}

      - name: Update PlatformIO on failure
        run: pio pkg update
        if: ${{ failure() }}
...
